# =================================================================
# Codemagic CI/CD Configuration for Cordova/Ionic Project
# FINAL FINAL FINAL FINAL ATTEMPT - Advanced Clean + Apple Distribution
# =================================================================
workflows:
  cordova-build-workflow:
    name: Cordova iOS & Android CI/CD
    
    # 1. تنظیم سخت‌افزار
    instance_type: mac_mini_m1
      
    # 2. تنظیم محیط (Environment)
    environment:
      vars:
        NODE_VERSION: 20
        CORDOVA_VERSION: 12
        ANDROID_PLATFORM_VERSION: 13.0.0
        IOS_TEAM_ID: 72M97MR8UU     # Team ID شما (از Codemagic)
        IOS_SCHEME_NAME: Farra      # نام Scheme پروژه شما
        
      node: $NODE_VERSION
      
    # 3. مراحل بیلد (Scripts)
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova@$CORDOVA_VERSION

      - name: Install Project Dependencies
        script: npm install
        
      - name: Add Platforms and Prepare
        script: | 
          # افزودن پلتفرم‌ها
          cordova platform add ios --save || true
          cordova platform add android@$ANDROID_PLATFORM_VERSION --save || true
          cordova prepare
          
      - name: CRITICAL-FIX-Advanced-Xcode-Project-Cleanup 
        script: |
          echo "Applying Advanced Cleanup to project files to resolve Code Signing conflicts..."
          
          # فایل پروژه اصلی
          PROJ_FILE_FARRA="platforms/ios/${IOS_SCHEME_NAME}.xcodeproj/project.pbxproj"
          
          # فایل پروژه CordovaLib (در این مرحله فقط Deployment Target را فیکس می‌کنیم)
          PROJ_FILE_CORDOVA="platforms/ios/CordovaLib/CordovaLib.xcodeproj/project.pbxproj"
          
          # استفاده از for برای اعمال اصلاحات
          for PROJ_FILE in $PROJ_FILE_FARRA $PROJ_FILE_CORDOVA; do
            if [ -f "$PROJ_FILE" ]; then
              echo "Processing $PROJ_FILE"
              
              # 1. تنظیم IPHONEOS_DEPLOYMENT_TARGET به 12.0
              sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/g' $PROJ_FILE
              
              # **فقط برای Farra.xcodeproj:** حذف تنظیمات تداخلی
              if [ "$PROJ_FILE" = "$PROJ_FILE_FARRA" ]; then
                  echo "Applying signing cleanups to Farra.xcodeproj..."
                  # 2. حذف کامل تمام رفرنس‌های Manual Signing
                  sed -i '' '/ProvisioningStyle = Manual;/d' $PROJ_FILE
                  
                  # 3. حذف رفرنس‌های قدیمی iPhone Distribution (به صورت تهاجمی)
                  sed -i '' '/CODE_SIGN_IDENTITY = "iPhone Distribution"/d' $PROJ_FILE
                  
                  # 4. حذف رفرنس‌های تیم (احتمالی)
                  sed -i '' '/DevelopmentTeam/d' $PROJ_FILE
              fi
              
              echo "Finished processing $PROJ_FILE."
            else
              echo "Error: Project file $PROJ_FILE not found (this should not happen)."
            fi
          done
          
      - name: Build iOS Release (Direct Xcode Archive)
        script: | 
          echo "Starting iOS Archive build for Distribution..."
          # تزریق تنظیمات امضا:
          # - DEVELOPMENT_TEAM: اجبار به استفاده از Team ID شما (که با API Key در Codemagic ست شده است)
          # - CODE_SIGN_STYLE: اجبار به Automatic (اگر Xcode آن را دستی می‌بیند)
          # - CODE_SIGN_IDENTITY: استفاده از "Apple Distribution" که هویت صحیح برای توزیع API Key است
          xcodebuild -workspace platforms/ios/${IOS_SCHEME_NAME}.xcworkspace \
            -scheme ${IOS_SCHEME_NAME} \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive \
            archive \
            DEVELOPMENT_TEAM=${IOS_TEAM_ID} \
            CODE_SIGN_STYLE="Automatic" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            IPHONEOS_DEPLOYMENT_TARGET="12.0"
          
      - name: Export IPA from Archive
        script: |
          echo "Exporting IPA..."
          # اطمینان حاصل می‌کنیم که ExportOptions.plist برای App Store/Distribution تنظیم شده باشد
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive -exportPath $CM_BUILD_DIR/build/Release-iphoneos -exportOptionsPlist platforms/ios/exportOptions.plist
          
      - name: Build Android Release (AAB for Google Play)
        script: |
          echo "Starting Android AAB build for Google Play..."
          cordova build android --release -- -- --packageType=bundle
          
    # 4. خروجی‌ها (Artifacts)
    artifacts:
      - $CM_BUILD_DIR/build/Release-iphoneos/*.ipa
      - platforms/android/app/build/outputs/bundle/release/*.aab
      - /tmp/codemagic-temp/build_log_*.txt
      
    # 5. تنظیمات انتشار (Publishing)
    publishing:
      email:
        recipients: 
          - farokgraphic@gmail.com
        notify:
          success: true
          failure: true
