# =================================================================
# Codemagic CI/CD Configuration - FINAL FIX based on NEW TOOL API
# =================================================================
workflows:
  cordova-ios-final-automatic-workflow-v2:
    name: Cordova iOS Final Automatic Signing Fix (v2)
    
    instance_type: mac_mini_m1
      
    environment:
      vars:
        NODE_VERSION: 20
        CORDOVA_VERSION: 12
        IOS_SCHEME_NAME: Farra
        
      node: $NODE_VERSION
      
    scripts:
      - name: Install Dependencies
        script: | 
          npm install -g cordova@$CORDOVA_VERSION
          npm install
        
      - name: Prepare iOS Project from a Clean Slate
        script: |
          echo "Removing platforms/ios for a fresh start..."
          rm -rf platforms/ios
          cordova platform add ios --save
          # نیازی به cordova prepare نیست چون build آن را انجام می‌دهد
          
      - name: Codemagic Code Signing (Fetching Files Only)
        # 1. بازیابی فایل‌های امضا 
        # حذف پارامتر --team-id که دیگر شناخته نمی‌شود.
        # Codemagic انتظار دارد Team ID را از متغیر محیطی یا API Key بخواند.
        script: |
          echo "Fetching Code Signing Files..."
          app-store-connect fetch-signing-files "$IOS_SCHEME_NAME" --type IOS_APP_STORE
          
      - name: Build iOS Release (Using Cordova and Codemagic Fix)
        script: | 
          echo "Starting final iOS Cordova build..."
          # Cordova از فایل‌های دانلود شده توسط Codemagic استفاده خواهد کرد.
          # توجه: در نسخه‌های جدید، xcode-project use-automatic-signing
          # جای خود را به استفاده خودکار Cordova از گواهی‌های دانلود شده داده است.
          cordova build ios --release 
          
      - name: Export IPA Artifacts
        script: |
          echo "Exporting IPA with Codemagic's export utility..."
          # این دستور (use-profiles) به Xcode کمک می کند تا از گواهی های دانلود شده استفاده کند.
          xcode-project use-profiles 
          
          # اجرای دستور Export استاندارد
          xcodebuild -exportArchive \
            -archivePath platforms/ios/build/Farra.xcarchive \
            -exportPath $CM_BUILD_DIR/output \
            -exportOptionsPlist $CM_BUILD_DIR/codemagic/export_options.plist
          
    # 4. خروجی‌ها (Artifacts)
    artifacts:
      - $CM_BUILD_DIR/output/*.ipa
      - /tmp/codemagic-temp/build_log_*.txt
      
    # 5. تنظیمات انتشار (Publishing)
    publishing:
      email:
        recipients: 
          - farokgraphic@gmail.com
        notify:
          success: true
          failure: true
