# =================================================================
# Codemagic CI/CD Configuration for Cordova/Ionic Project
# FINAL FIX FOR CODE SIGNING (DEVELOPMENT_TEAM INJECTION)
# =================================================================
workflows:
  cordova-build-workflow:
    name: Cordova iOS & Android CI/CD
    
    # 1. تنظیم سخت‌افزار: mac_mini_m1 برای بیلد iOS الزامی است.
    instance_type: mac_mini_m1
      
    # 2. تنظیم محیط (Environment)
    environment:
      vars:
        NODE_VERSION: 20
        CORDOVA_VERSION: 12
        ANDROID_PLATFORM_VERSION: 13.0.0
        IOS_TEAM_ID: 72M97MR8UU # Team ID شما برای تزریق آسان
        IOS_SCHEME_NAME: Farra   # نام Scheme پروژه شما
        
      # تعریف ابزارها در سطح environment
      node: $NODE_VERSION
      
    # 3. مراحل بیلد (Scripts)
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova@$CORDOVA_VERSION

      - name: Install Project Dependencies
        script: npm install
        
      - name: Add Platforms
        script: | 
          # استفاده از '|| true' برای جلوگیری از خطا اگر پلتفرم قبلا وجود داشت
          cordova platform add ios --save || true
          cordova platform add android@$ANDROID_PLATFORM_VERSION --save || true
          # مطمئن شدن از آماده سازی پلتفرم‌ها برای بیلد
          cordova prepare
          
      - name: Build iOS Release (Direct Xcode Archive) - Code Signing Fix
        script: | 
          echo "Starting iOS Archive build for Distribution..."
          # تزریق DEVELOPMENT_TEAM برای رفع خطای "requires a development team"
          # از متغیرهای تعریف شده در Environment استفاده می‌کنیم.
          xcodebuild -workspace platforms/ios/${IOS_SCHEME_NAME}.xcworkspace \
            -scheme ${IOS_SCHEME_NAME} \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive \
            archive \
            DEVELOPMENT_TEAM=${IOS_TEAM_ID}
          
      - name: Export IPA from Archive
        script: |
          echo "Exporting IPA..."
          # این مرحله آرشیو را با استفاده از API Key ذخیره شده در Codemagic به فایل IPA تبدیل می‌کند.
          # توجه: نام فایل archivePath باید با مرحله قبل یکسان باشد.
          # همچنین exportOptions.plist باید موجود باشد.
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive -exportPath $CM_BUILD_DIR/build/Release-iphoneos -exportOptionsPlist platforms/ios/exportOptions.plist
          
      - name: Build Android Release (AAB for Google Play)
        script: |
          echo "Starting Android AAB build for Google Play..."
          # بیلد AAB (Android App Bundle) فرمت ترجیحی Google Play است
          # برای موفقیت، Keystore باید در تنظیمات Codemagic آپلود شده باشد.
          cordova build android --release -- -- --packageType=bundle
          
    # 4. خروجی‌ها (Artifacts)
    artifacts:
      # مسیر فایل IPA خروجی گرفته شده از مرحله Export IPA
      - $CM_BUILD_DIR/build/Release-iphoneos/*.ipa
      # مسیر فایل AAB برای Google Play
      - platforms/android/app/build/outputs/bundle/release/*.aab
      - /tmp/codemagic-temp/build_log_*.txt
      
    # 5. تنظیمات انتشار (Publishing)
    publishing:
      email:
        recipients: 
          - farokgraphic@gmail.com # ایمیل شما
        notify:
          success: true
          failure: true
