# =================================================================
# Codemagic CI/CD Configuration for Cordova/Ionic Project
# FINAL FINAL FINAL ATTEMPT - Remove SED, use xcodebuild parameters
# =================================================================
workflows:
  cordova-build-workflow:
    name: Cordova iOS & Android CI/CD
    
    # 1. تنظیم سخت‌افزار
    instance_type: mac_mini_m1
      
    # 2. تنظیم محیط (Environment)
    environment:
      vars:
        NODE_VERSION: 20
        CORDOVA_VERSION: 12
        ANDROID_PLATFORM_VERSION: 13.0.0
        IOS_TEAM_ID: 72M97MR8UU     # Team ID شما (از Codemagic)
        IOS_SCHEME_NAME: Farra      # نام Scheme پروژه شما
        
      node: $NODE_VERSION
      
    # 3. مراحل بیلد (Scripts)
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova@$CORDOVA_VERSION

      - name: Install Project Dependencies
        script: npm install
        
      - name: Add Platforms and Prepare
        script: | 
          # افزودن پلتفرم‌ها
          cordova platform add ios --save || true
          cordova platform add android@$ANDROID_PLATFORM_VERSION --save || true
          
          # این دستور Cordova Deployment Target را به 12.0 در config.xml به‌روز می‌کند
          # و آماده‌سازی را انجام می‌دهد
          cordova prepare
          
      - name: CRITICAL-FIX-Deployment-Target
        script: |
          echo "Forcing Deployment Target to 12.0 to clear warnings (Farra.xcodeproj)..."
          PROJ_FILE="platforms/ios/${IOS_SCHEME_NAME}.xcodeproj/project.pbxproj"
          # تنظیم IPHONEOS_DEPLOYMENT_TARGET در Farra.xcodeproj به 12.0
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/g' $PROJ_FILE
          
      - name: Build iOS Release (Direct Xcode Archive)
        script: | 
          echo "Starting iOS Archive build for Distribution..."
          # استفاده از xcodebuild با تزریق کامل تنظیمات امضا
          # CODE_SIGN_IDENTITY="iPhone Distribution" برای امضای تولیدی/API Key
          # PROVISIONING_PROFILE_SPECIFIER="" برای اجبار به استفاده از پروفایل Codemagic
          xcodebuild -workspace platforms/ios/${IOS_SCHEME_NAME}.xcworkspace \
            -scheme ${IOS_SCHEME_NAME} \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive \
            archive \
            DEVELOPMENT_TEAM=${IOS_TEAM_ID} \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            IPHONEOS_DEPLOYMENT_TARGET="12.0" # تکرار تنظیم Deployment Target
          
      - name: Export IPA from Archive
        script: |
          echo "Exporting IPA..."
          # اطمینان حاصل می‌کنیم که ExportOptions.plist برای App Store/Distribution تنظیم شده باشد
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive -exportPath $CM_BUILD_DIR/build/Release-iphoneos -exportOptionsPlist platforms/ios/exportOptions.plist
          
      - name: Build Android Release (AAB for Google Play)
        script: |
          echo "Starting Android AAB build for Google Play..."
          cordova build android --release -- -- --packageType=bundle
          
    # 4. خروجی‌ها (Artifacts)
    artifacts:
      - $CM_BUILD_DIR/build/Release-iphoneos/*.ipa
      - platforms/android/app/build/outputs/bundle/release/*.aab
      - /tmp/codemagic-temp/build_log_*.txt
      
    # 5. تنظیمات انتشار (Publishing)
    publishing:
      email:
        recipients: 
          - farokgraphic@gmail.com
        notify:
          success: true
          failure: true
