# =================================================================
# Codemagic CI/CD Configuration for Cordova/Ionic Project
# AGGRESSIVE FIX: Clears ALL conflicting Code Signing settings
# =================================================================
workflows:
  cordova-build-workflow:
    name: Cordova iOS & Android CI/CD
    
    # 1. تنظیم سخت‌افزار
    instance_type: mac_mini_m1
      
    # 2. تنظیم محیط (Environment)
    environment:
      vars:
        NODE_VERSION: 20
        CORDOVA_VERSION: 12
        ANDROID_PLATFORM_VERSION: 13.0.0
        IOS_TEAM_ID: 72M97MR8UU     # Team ID شما
        IOS_SCHEME_NAME: Farra      # نام Scheme پروژه شما
        
      # تعریف ابزارها در سطح environment
      node: $NODE_VERSION
      
    # 3. مراحل بیلد (Scripts)
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova@$CORDOVA_VERSION

      - name: Install Project Dependencies
        script: npm install
        
      - name: Add Platforms
        script: | 
          # افزودن پلتفرم‌ها
          cordova platform add ios --save || true
          cordova platform add android@$ANDROID_PLATFORM_VERSION --save || true
          cordova prepare
          
      - name: Clean Xcode Code Signing Settings & Fix Warnings (CRITICAL FIX)
        script: |
          echo "Applying AGGRESSIVE fix to Xcode project files to clear Code Signing conflicts..."
          
          # تعریف مسیر هر دو فایل پروژه (Farra و CordovaLib)
          PROJ_FILES="platforms/ios/${IOS_SCHEME_NAME}.xcodeproj/project.pbxproj platforms/ios/CordovaLib/CordovaLib.xcodeproj/project.pbxproj"
          
          # اجرای دستورات sed برای هر دو فایل
          for PROJ_FILE in $PROJ_FILES; do
            if [ -f "$PROJ_FILE" ]; then
              echo "Processing $PROJ_FILE"
              
              # 1. FORCE Provisioning Style to Automatic
              # تغییر ProvisioningStyle از Manual به Automatic
              sed -i '' 's/ProvisioningStyle = Manual;/ProvisioningStyle = Automatic;/g' $PROJ_FILE

              # 2. AGGRESSIVE Clean: Neutralize ALL Code Signing Identity settings
              # تنظیم CODE_SIGN_IDENTITY روی یک مقدار خالی برای همه حالت‌ها
              sed -i '' 's/CODE_SIGN_IDENTITY = .*;/CODE_SIGN_IDENTITY = ""/g' $PROJ_FILE
              sed -i '' 's/CODE_SIGN_IDENTITY\[sdk=iphoneos\*\] = .*;/CODE_SIGN_IDENTITY\[sdk=iphoneos\*\] = ""/g' $PROJ_FILE
              
              # 3. Remove all Provisioning Profile Specifier/Team entries
              # حذف تنظیمات مربوط به پروفایل‌های دستی و Team ID ذخیره شده در فایل
              sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' $PROJ_FILE
              sed -i '' '/PROVISIONING_PROFILE/d' $PROJ_FILE
              sed -i '' '/DEVELOPMENT_TEAM/d' $PROJ_FILE
              
              # 4. Fix iOS Deployment Target warning (11.0 to 12.0)
              sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/g' $PROJ_FILE
              sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/g' $PROJ_FILE
            fi
          done
          
      - name: Build iOS Release (Direct Xcode Archive)
        script: | 
          echo "Starting iOS Archive build for Distribution..."
          # تزریق DEVELOPMENT_TEAM برای استفاده از API Key Codemagic
          xcodebuild -workspace platforms/ios/${IOS_SCHEME_NAME}.xcworkspace \
            -scheme ${IOS_SCHEME_NAME} \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive \
            archive \
            DEVELOPMENT_TEAM=${IOS_TEAM_ID}
          
      - name: Export IPA from Archive
        script: |
          echo "Exporting IPA..."
          # فرض بر این است که exportOptions.plist در مسیر platforms/ios/ موجود است.
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive -exportPath $CM_BUILD_DIR/build/Release-iphoneos -exportOptionsPlist platforms/ios/exportOptions.plist
          
      - name: Build Android Release (AAB for Google Play)
        script: |
          echo "Starting Android AAB build for Google Play..."
          cordova build android --release -- -- --packageType=bundle
          
    # 4. خروجی‌ها (Artifacts)
    artifacts:
      - $CM_BUILD_DIR/build/Release-iphoneos/*.ipa
      - platforms/android/app/build/outputs/bundle/release/*.aab
      - /tmp/codemagic-temp/build_log_*.txt
      
    # 5. تنظیمات انتشار (Publishing)
    publishing:
      email:
        recipients: 
          - farokgraphic@gmail.com
        notify:
          success: true
          failure: true
