# =================================================================
# Codemagic CI/CD Configuration for Cordova/Ionic Project
# =================================================================
workflows:
  cordova-build-workflow:
    name: Cordova iOS & Android CI/CD
    
    # نوع سخت‌افزار مورد استفاده برای بیلد (معمولاً Mac Mini M1 برای بیلد iOS لازم است)
    instance_type: mac_mini_m1
    
    # تعریف نسخه سیستم‌عامل مک و ابزارهای مورد نیاز
    # macOS و Xcode باید مستقیماً زیر workflow باشند، نه زیر environment
    macos:
      version: 13
      
    environment:
      # تنظیمات متغیرهای محیطی
      vars:
        # نسخه Node.js (برای Cordova/NPM)
        NODE_VERSION: 20
        # نسخه Cordova CLI
        CORDOVA_VERSION: 12
        # نسخه Android Platform (معمولاً 13.0.0 پایدار است)
        ANDROID_PLATFORM_VERSION: 13.0.0
        
      # تعریف ابزارها در سطح environment
      node: $NODE_VERSION
      
      # ابزارهای اضافی که Codemagic باید آماده کند
      # این ابزارها به صورت خودکار نصب و در دسترس قرار می‌گیرند.
      # فقط نیاز است که نسخه‌شان به صورت متغیر در scripts استفاده شود.

    # ------------------
    # مراحل بیلد
    # ------------------
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova@$CORDOVA_VERSION

      - name: Install Project Dependencies
        script: npm install
        
      - name: Add Platforms
        script: | 
          # افزودن پلتفرم iOS
          cordova platform add ios --save || true
          # افزودن پلتفرم Android
          cordova platform add android@$ANDROID_PLATFORM_VERSION --save || true

      - name: Build iOS Release
        script: | 
          # توجه: برای بیلد موفق iOS باید Code Signing در تنظیمات Codemagic انجام شود.
          echo "Starting iOS build..."
          cordova build ios --release --buildFlag='-allowProvisioningUpdates'
      
      - name: Build Android Release
        script: |
          echo "Starting Android build..."
          cordova build android --release
          
    # ------------------
    # خروجی‌ها (Artifacts)
    # ------------------
    artifacts:
      - build/Release-iphoneos/*.ipa # خروجی iOS
      - platforms/android/app/build/outputs/apk/release/*.apk # خروجی Android
      - /tmp/codemagic-temp/build_log_*.txt # فایل گزارش
      
    # ------------------
    # تنظیمات انتشار (Publishing)
    # ------------------
    publishing:
      # بخش Code Signing برای iOS باید پس از تکمیل تنظیمات در Codemagic فعال شود.
      email:
        recipients: 
          - mohammad.babelly@example.com # ایمیل خودت رو اینجا بگذار
        triggering:
          - success
          - failure
