# =================================================================
# Codemagic CI/CD Configuration for Cordova/Ionic Project
# FINAL ATTEMPT - Simplified and Targeted Aggressive Code Signing Fix
# =================================================================
workflows:
  cordova-build-workflow:
    name: Cordova iOS & Android CI/CD
    
    # 1. تنظیم سخت‌افزار
    instance_type: mac_mini_m1
      
    # 2. تنظیم محیط (Environment)
    environment:
      vars:
        NODE_VERSION: 20
        CORDOVA_VERSION: 12
        ANDROID_PLATFORM_VERSION: 13.0.0
        IOS_TEAM_ID: 72M97MR8UU     # Team ID شما
        IOS_SCHEME_NAME: Farra      # نام Scheme پروژه شما
        
      node: $NODE_VERSION
      
    # 3. مراحل بیلد (Scripts)
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova@$CORDOVA_VERSION

      - name: Install Project Dependencies
        script: npm install
        
      - name: Add Platforms and Prepare
        script: | 
          # افزودن پلتفرم‌ها
          cordova platform add ios --save || true
          cordova platform add android@$ANDROID_PLATFORM_VERSION --save || true
          cordova prepare
          
      - name: CRITICAL FIX: Aggressively Clean Xcode Project File
        script: |
          echo "Applying AGGRESSIVE fix to Farra.xcodeproj to clear Code Signing conflicts..."
          
          # مسیر فایل پروژه اصلی
          PROJ_FILE="platforms/ios/${IOS_SCHEME_NAME}.xcodeproj/project.pbxproj"
          
          if [ -f "$PROJ_FILE" ]; then
            echo "Processing $PROJ_FILE"
            
            # 1. FORCE Provisioning Style to Automatic
            # تغییر ProvisioningStyle از Manual به Automatic
            # استفاده از پرچم -i که سازگارتر است (بدون پسوند)
            sed -i 's/ProvisioningStyle = Manual;/ProvisioningStyle = Automatic;/g' $PROJ_FILE

            # 2. Neutralize ALL Code Signing Identity settings (تغییر به مقدار خالی)
            # این قوی‌ترین راه برای پاک کردن تداخل "iPhone Distribution" است.
            sed -i 's/CODE_SIGN_IDENTITY = .*;/CODE_SIGN_IDENTITY = ""/g' $PROJ_FILE
            
            # 3. Fix iOS Deployment Target warning (11.0 to 12.0)
            sed -i 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/g' $PROJ_FILE
            
            echo "Finished cleaning $PROJ_FILE."
          else
            echo "Error: Project file $PROJ_FILE not found."
          fi
          
      - name: Build iOS Release (Direct Xcode Archive)
        script: | 
          echo "Starting iOS Archive build for Distribution..."
          # تزریق DEVELOPMENT_TEAM برای استفاده از API Key Codemagic
          xcodebuild -workspace platforms/ios/${IOS_SCHEME_NAME}.xcworkspace \
            -scheme ${IOS_SCHEME_NAME} \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive \
            archive \
            DEVELOPMENT_TEAM=${IOS_TEAM_ID}
          
      - name: Export IPA from Archive
        script: |
          echo "Exporting IPA..."
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/${IOS_SCHEME_NAME}.xcarchive -exportPath $CM_BUILD_DIR/build/Release-iphoneos -exportOptionsPlist platforms/ios/exportOptions.plist
          
      - name: Build Android Release (AAB for Google Play)
        script: |
          echo "Starting Android AAB build for Google Play..."
          cordova build android --release -- -- --packageType=bundle
          
    # 4. خروجی‌ها (Artifacts)
    artifacts:
      - $CM_BUILD_DIR/build/Release-iphoneos/*.ipa
      - platforms/android/app/build/outputs/bundle/release/*.aab
      - /tmp/codemagic-temp/build_log_*.txt
      
    # 5. تنظیمات انتشار (Publishing)
    publishing:
      email:
        recipients: 
          - farokgraphic@gmail.com
        notify:
          success: true
          failure: true
