# =================================================================
# Codemagic CI/CD Configuration for Cordova/Ionic Project (Final Fix)
# =================================================================
workflows:
  cordova-build-workflow:
    name: Cordova iOS & Android CI/CD
    
    # 1. تنظیم سخت‌افزار (در سطح workflow)
    instance_type: mac_mini_m1
    macos:
      version: 13
      
    # 2. تنظیم محیط (Environment)
    environment:
      vars:
        NODE_VERSION: 20
        CORDOVA_VERSION: 12
        ANDROID_PLATFORM_VERSION: 13.0.0
        
      # تعریف ابزارها در سطح environment
      node: $NODE_VERSION
      
    # 3. مراحل بیلد (Scripts)
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova@$CORDOVA_VERSION

      - name: Install Project Dependencies
        script: npm install
        
      - name: Add Platforms
        script: | 
          cordova platform add ios --save || true
          cordova platform add android@$ANDROID_PLATFORM_VERSION --save || true

      - name: Build iOS Release
        script: | 
          echo "Starting iOS build..."
          # پرچم -allowProvisioningUpdates برای مدیریت خودکار گواهی‌ها در Xcode است.
          cordova build ios --release --buildFlag='-allowProvisioningUpdates'
      
      - name: Build Android Release
        script: |
          echo "Starting Android build..."
          # توجه: برای بیلد Android نهایی، لازم است KeyStore را در Codemagic آپلود و در این اسکریپت استفاده کنیم.
          cordova build android --release
          
    # 4. خروجی‌ها (Artifacts)
    artifacts:
      - build/Release-iphoneos/*.ipa
      - platforms/android/app/build/outputs/apk/release/*.apk
      - /tmp/codemagic-temp/build_log_*.txt
      
    # 5. تنظیمات انتشار (Publishing)
    publishing:
      email:
        recipients: 
          - mohammad.babelly@example.com # ایمیل خودت رو اینجا بگذار
        # اصلاح خطا: به جای 'triggering' از 'notify' استفاده می‌شود.
        notify:
          success: true
          failure: true
